name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PORT: 3001

    outputs:
      port: ${{ env.PORT }}

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image using Docker Compose
        run: docker-compose -f docker-compose.yml build

  verify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Run and verify the Docker container
        env:
          PORT: ${{ needs.build.outputs.port }}
        run: |
          docker-compose -f docker-compose.yml up -d
          echo "Waiting for the container to start..."

          # Poll the service until it responds
          for i in {1..10}; do
            curl -f http://localhost:${PORT} && break || sleep 5
          done

          echo "Service is up and running!"
          docker ps  # Check running containers
